server:
  port: 8088
spring:
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
    datasource:
      names: master,slave
      master:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: 'jdbc:mysql://10.10.10.120:3307/reggie'
        username: root
        password: admin
      slave:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: 'jdbc:mysql://10.10.10.120:3308/reggie'
        username: root
        password: admin
    props:
      sql-show: false
    rules:
      readwrite-splitting:
        load-balancers:
          round-robin:
            type: ROUND_ROBIN
        data-sources:
          ms:
            static-strategy:
              write-data-source-name: master
              read-data-source-names:
                - slave
            load-balancer-name: round-robin
  web:
    resources:
      static-locations: classpath:/reggie
  redis:
    database: 0
    port: 6379
    password: 00000...
    host: 120.46.151.166
  cache:
    redis:
      time-to-live: 3600000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    global-config:
      db-config:
        id-type: ASSIGN_ID
file-save:
  path: /Users/lisang/Documents/imgs/
sa-token:
  token-name: reggie
  timeout: 259200
  is-concurrent: false
  token-style: uuid
  is-log: false